{% set name = "run_dbcan" %}
{% set version = "2.0.0" %}
package:
  name:"{{ name|lower }}"
  version:"{{ version }}"

source:
  git_rev:2.0.0
  git_url:https://github.com/linnabrown/run_dbcan.git

requirements:
  build:
    - python
    - setuptools
    - natsort

  run:
    - python

test:
  imports:
    - run_dbcan

about:
  home: https://bcb.unl.edu/dbCAN2
  license: GUN-3.0
  license_family: GNU
  summary: a tool to search CAZyme Family of input gene.
