{% set name = "run_dbcan" %}
{% set version = "3.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  #  git_url: https://github.com/linnabrown/run_dbcan.git  #uncomment this when merging into main repo
  git_url: https://github.com/AlexSCFraser/run_dbcan.git #delete this when merging into main repo
  git_depth: 1 # only grab most recent commit on branch

requirements:
  build:
    - python
    - setuptools
    - git
  host:
    - python
  run:
    - diamond
    - hmmer
    - prodigal
    - python
    - natsort
    - scipy
    - psutil
    - numpy

about:
  home: http://bcb.unl.edu/dbCAN2/
  dev_url: https://github.com/linnabrown/run_dbcan
  license: GPLv3
  license_file: LICENSE
  summary: A standalone tool of http://bcb.unl.edu/dbCAN2/
